/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "e619e8606099384540d70eeaaa8091752b1bebe9"
 * GIT_BRANCH      "STAI-2.2"
 * GIT_DESCRIPTION "atonn-v1.1.1-14-ge619e860"
 *
 * Command Line options:
 * --load-mdesc-file = "/opt/ST/STEdgeAI/2.2/Utilities/configs/stm32n6"
 * --load-mpool-file = "/home/rama/STM32CubeAi/test_lenet5/.ai/memory_pool"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "/home/rama/STM32CubeAi/test_lenet5/.ai/st_ai_output/lenet5_mnist_pruned_quantized_OE_3_3_0_Q.json"
 * --Os = true
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "/home/rama/STM32CubeAi/test_lenet5/.ai/st_ai_output/lenet5_mnist_pruned_quantized_OE_3_3_0.onnx"
 * --out-dir-prefix = "/home/rama/STM32CubeAi/test_lenet5/.ai/st_ai_ws/neural_art__network/"
 * --mvei = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 1 || LL_ATON_VERSION_DEV != 14
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 8 is 19.01 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  absolute_mode size=117440504 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
/* global pool 1 is 1.61 KB */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.88 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=85  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_Default(uint32_t num, void* buffer, uint32_t size)
{
  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_Default(uint32_t num)
{
  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_Default(uint32_t num, void* buffer, uint32_t size)
{
  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_Default(uint32_t num)
{
  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=22  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_Default_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_Default_1') start function
static void _ec_blob_cache_start_func_1(const void *epoch_block) {
  LL_ATON_LIB_UNUSED(epoch_block);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 64))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) /* Equivalent hex address = 0x342e0020UL */, 32);

};


/* scheduling DONE                 ------------------------------------------------------------------- */

const EpochBlock_ItemTypeDef *LL_ATON_EpochBlockItems_Default(void) {

  static const EpochBlock_ItemTypeDef ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_Default_1),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw | (LL_ATON_EC_MustDecryptBlob_Default__ec_blob_Default_1 ? EpochBlock_Flags_blob_encrypted : EpochBlock_Flags_NONE),
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 8,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_Default(void)
{
  static const uint32_t buff_info__shape_1_1_28_28[] = { 1, 28, 28, 1 };
  static const uint32_t buff_info__mem_shape_F_1_1_28_28[] = { 1, 1, 28, 28 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.0127282338216901 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -95 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_57_256_1_1[] = { 57, 1, 1, 256 };
  static const uint32_t buff_info__mem_shape_M128_57_256_1_1[] = { 57, 2, 1, 1, 128 };
  static const float buff_info_Gemm_13_weights_transposed_3_quant_scale[] = { 0.00226436648517847, 0.00246811285614967, 0.00192895520012826, 0.00244703888893127, 0.00284019904211164, 0.00216230168007314, 0.00250562140718102, 0.00281504448503256, 0.00180073850788176, 0.00223713950254023, 0.00215261802077293, 0.00244987942278385, 0.00406384281814098, 0.00217545055784285, 0.00273180427029729, 0.00239860801957548, 0.00270199775695801, 0.00226025958545506, 0.00321195414289832, 0.00369534641504288, 0.00344092724844813, 0.00230556377209723, 0.00213148049078882, 0.00399826327338815, 0.00182054319884628, 0.00233441800810397, 0.00226455880329013, 0.00245852465741336, 0.00168328173458576, 0.00269203307107091, 0.00185341178439558, 0.00185453135054559, 0.00223825220018625, 0.00222569960169494, 0.0026021299418062, 0.0019777852576226, 0.0024937407579273, 0.00241451989859343, 0.00247240555472672, 0.00175513059366494, 0.00200767954811454, 0.00220680702477694, 0.00221130112186074, 0.00230212928727269, 0.00199843035079539, 0.00333580304868519, 0.00204398017376661, 0.00184928614180535, 0.00197887723334134, 0.00229715136811137, 0.00180032127536833, 0.00183583260513842, 0.00298252957873046, 0.00152877508662641, 0.00225123134441674, 0.00227702758274972, 0.00251560122705996 };
  static const int16_t buff_info_Gemm_13_weights_transposed_3_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_34_57_1_1[] = { 34, 1, 1, 57 };
  static const uint32_t buff_info__mem_shape_F_34_57_1_1[] = { 34, 57, 1, 1 };
  static const float buff_info_Gemm_14_weights_transposed_9_quant_scale[] = { 0.00192101835273206, 0.00221423991024494, 0.00193683651741594, 0.00205953605473042, 0.0020647153723985, 0.00167694443371147, 0.00189225329086185, 0.00245942524634302, 0.00213012797757983, 0.00173921801615506, 0.00198428053408861, 0.00151393166743219, 0.00204326561652124, 0.00245251529850066, 0.0018595902947709, 0.00235729431733489, 0.00233974843285978, 0.00181387388147414, 0.00220920261926949, 0.0019344404572621, 0.00170771486591548, 0.00170671730302274, 0.00171833217609674, 0.00251567550003529, 0.00221844390034676, 0.00186218996532261, 0.00211952324025333, 0.00168333295732737, 0.00241447449661791, 0.0016249023610726, 0.00175456935539842, 0.0020336180459708, 0.00153525045607239, 0.00227411254309118 };
  static const int16_t buff_info_Gemm_14_weights_transposed_9_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_10_34_1_1[] = { 10, 1, 1, 34 };
  static const uint32_t buff_info__mem_shape_F_10_34_1_1[] = { 10, 34, 1, 1 };
  static const float buff_info_Gemm_15_weights_transposed_15_quant_scale[] = { 0.00208582426421344, 0.00192134792450815, 0.00252950727008283, 0.00211564591154456, 0.00225297198630869, 0.00179342902265489, 0.00245814491063356, 0.00179018068592995, 0.00219372077845037, 0.00186750397551805 };
  static const int16_t buff_info_Gemm_15_weights_transposed_15_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_6_1_3_5[] = { 6, 3, 5, 1 };
  static const uint32_t buff_info__mem_shape_F_6_1_3_5[] = { 6, 1, 3, 5 };
  static const float buff_info_Conv2D_4_weights_submask_0_0_0_0_6_1_3_5_64_quant_scale[] = { 0.00338373705744743, 0.00461629731580615, 0.00477350736036897, 0.00454768352210522, 0.0023799086920917, 0.00389960245229304 };
  static const int16_t buff_info_Conv2D_4_weights_submask_0_0_0_0_6_1_3_5_64_quant_offset[] = { 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_6_1_2_5[] = { 6, 2, 5, 1 };
  static const uint32_t buff_info__mem_shape_F_6_1_2_5[] = { 6, 1, 2, 5 };
  static const float buff_info_Conv2D_4_weights_submask_0_0_3_0_6_1_2_5_65_quant_scale[] = { 0.00338373705744743, 0.00461629731580615, 0.00477350736036897, 0.00454768352210522, 0.0023799086920917, 0.00389960245229304 };
  static const int16_t buff_info_Conv2D_4_weights_submask_0_0_3_0_6_1_2_5_65_quant_offset[] = { 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_16_6_3_5[] = { 16, 3, 5, 6 };
  static const uint32_t buff_info__mem_shape_M3_16_6_3_5[] = { 16, 2, 3, 5, 3 };
  static const float buff_info_Conv2D_8_weights_submask_0_0_0_0_16_6_3_5_66_quant_scale[] = { 0.00278961146250367, 0.0023613553494215, 0.00340594607405365, 0.00271532987244427, 0.00225738761946559, 0.0036103306338191, 0.00326565117575228, 0.00214376277290285, 0.00307621131651103, 0.00249404180794954, 0.002040752209723, 0.00304542877711356, 0.00266880076378584, 0.0019709849730134, 0.00327068381011486, 0.00263491342775524 };
  static const int16_t buff_info_Conv2D_8_weights_submask_0_0_0_0_16_6_3_5_66_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_16_6_2_5[] = { 16, 2, 5, 6 };
  static const uint32_t buff_info__mem_shape_M3_16_6_2_5[] = { 16, 2, 2, 5, 3 };
  static const float buff_info_Conv2D_8_weights_submask_0_0_3_0_16_6_2_5_67_quant_scale[] = { 0.00278961146250367, 0.0023613553494215, 0.00340594607405365, 0.00271532987244427, 0.00225738761946559, 0.0036103306338191, 0.00326565117575228, 0.00214376277290285, 0.00307621131651103, 0.00249404180794954, 0.002040752209723, 0.00304542877711356, 0.00266880076378584, 0.0019709849730134, 0.00327068381011486, 0.00263491342775524 };
  static const int16_t buff_info_Conv2D_8_weights_submask_0_0_3_0_16_6_2_5_67_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 784,
      .offset_limit = 848,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_1_1_28_28,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1_28_28,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Gemm_13_weights_transposed_3",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 0,
      .offset_end = 14598,
      .offset_limit = 14664,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 128,
      .mem_shape = buff_info__mem_shape_M128_57_256_1_1,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_57_256_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_13_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_13_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_14_weights_transposed_9",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 14608,
      .offset_end = 16546,
      .offset_limit = 16616,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 57,
      .mem_shape = buff_info__mem_shape_F_34_57_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_34_57_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_14_weights_transposed_9_quant_scale,
      .offset = buff_info_Gemm_14_weights_transposed_9_quant_offset,
    },
    {
      .name = "Gemm_15_weights_transposed_15",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 18960,
      .offset_end = 19302,
      .offset_limit = 19368,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 34,
      .mem_shape = buff_info__mem_shape_F_10_34_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_10_34_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_15_weights_transposed_15_quant_scale,
      .offset = buff_info_Gemm_15_weights_transposed_15_quant_offset,
    },
    {
      .name = "Conv2D_4_weights_submask_0_0_0_0_6_1_3_5_64",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 19312,
      .offset_end = 19402,
      .offset_limit = 19472,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_6_1_3_5,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_6_1_3_5,
      .per_channel = 1,
      .scale = buff_info_Conv2D_4_weights_submask_0_0_0_0_6_1_3_5_64_quant_scale,
      .offset = buff_info_Conv2D_4_weights_submask_0_0_0_0_6_1_3_5_64_quant_offset,
    },
    {
      .name = "Conv2D_4_weights_submask_0_0_3_0_6_1_2_5_65",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 19408,
      .offset_end = 19468,
      .offset_limit = 19536,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_F_6_1_2_5,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_6_1_2_5,
      .per_channel = 1,
      .scale = buff_info_Conv2D_4_weights_submask_0_0_3_0_6_1_2_5_65_quant_scale,
      .offset = buff_info_Conv2D_4_weights_submask_0_0_3_0_6_1_2_5_65_quant_offset,
    },
    {
      .name = "Conv2D_8_weights_submask_0_0_0_0_16_6_3_5_66",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 16560,
      .offset_end = 18000,
      .offset_limit = 18064,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_M3_16_6_3_5,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_6_3_5,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_submask_0_0_0_0_16_6_3_5_66_quant_scale,
      .offset = buff_info_Conv2D_8_weights_submask_0_0_0_0_16_6_3_5_66_quant_offset,
    },
    {
      .name = "Conv2D_8_weights_submask_0_0_3_0_16_6_2_5_67",
      .addr_base = {(unsigned char *)(0x71000000UL) /* Equivalent hex address = 0x71000000UL */},
      .offset_start = 18000,
      .offset_end = 18960,
      .offset_limit = 19024,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 3,
      .mem_shape = buff_info__mem_shape_M3_16_6_2_5,
      .mem_ndims = 5,
      .chpos = CHPos_Mixed,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_6_2_5,
      .per_channel = 1,
      .scale = buff_info_Conv2D_8_weights_submask_0_0_3_0_16_6_2_5_67_quant_scale,
      .offset = buff_info_Conv2D_8_weights_submask_0_0_3_0_16_6_2_5_67_quant_offset,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_Default(void)
{
  static const uint32_t buff_info__shape_1_10[] = { 1, 1, 10, 1 };
  static const uint32_t buff_info__mem_shape_U_1_10[] = { 1, 10 };
  static const float buff_info_Quantize_16_out_0_quant_scale[] = { 0.260709822177887 };
  static const int16_t buff_info_Quantize_16_out_0_quant_offset[] = { -6 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_16_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 48,
      .offset_end = 58,
      .offset_limit = 128,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 7,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_10,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_10,
      .per_channel = 0,
      .scale = buff_info_Quantize_16_out_0_quant_scale,
      .offset = buff_info_Quantize_16_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_Default(void)
{
  return NULL;
}

